/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("FlightsObjectPageObjectPage journey");

        opaTest("Navigate to FlightsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheFlightsListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheFlightsListGenerated.onTable().iCheckRows();
            When.onTheFlightsListGenerated.onTable().iPressRow(0);

            Then.onTheFlightsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheFlightsObjectPageGenerated.iCheckSection({ section: "FieldGroup::GeneralData" });
            Then.onTheFlightsObjectPageGenerated.onForm({ section: "FieldGroup::GeneralData" }).iCheckField({ property: "flightDate" });
            Then.onTheFlightsObjectPageGenerated.onForm({ section: "FieldGroup::GeneralData" }).iCheckField({ property: "price" });
            Then.onTheFlightsObjectPageGenerated.onForm({ section: "FieldGroup::GeneralData" }).iCheckField({ property: "currency_code" });
            Then.onTheFlightsObjectPageGenerated.onForm({ section: "FieldGroup::GeneralData" }).iCheckField({ property: "bookedSeats" });
            Then.onTheFlightsObjectPageGenerated.onForm({ section: "FieldGroup::GeneralData" }).iCheckField({ property: "plannedSeats" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});